# ~/.config/fish/config.fish — LIVE-EDITABLE copy from the dendritic
# checkout (homeless-dotfiles policy #93, issue #98). Edits apply on the
# next fish start and are git-tracked; the equivalent option content in
# modules/features/fish/default.nix was ported here verbatim.
#
# Ported from the home-manager render of the fish feature module; keep the
# HM-generated bits that are still module-driven in sync:
#   - session vars (TERMINAL etc.) load from conf.d/00-hm-session-vars.fish
#     (module-regenerated on every switch so the store path never goes stale)
#   - completions ship via conf.d/plugin-*.fish and the
#     ~/.local/share/fish/home-manager/generated_completions path below

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

# Source handler functions

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- d docker
    abbr --add -- dc docker-compose
    abbr --add -- g git
    abbr --add -- ga 'git add'
    abbr --add -- gc 'git commit'
    abbr --add -- gp 'git push'
    abbr --add -- gpl 'git pull'
    abbr --add -- gs 'git status'
    abbr --add -- jc journalctl
    abbr --add -- n nvim
    abbr --add -- sc systemctl
    abbr --add -- v nvim
    abbr --add -- vim nvim

    # Aliases
    alias .. 'cd ..'
    alias ... 'cd ../..'
    alias asahi-rebuild 'sudo nixos-rebuild switch --impure --flake ~/.config/dendritic#ASAHI'
    alias cat 'bat --style=numbers,changes --color=always'
    alias cd z
    alias fzf 'fzf --height 40% --reverse --inline-info --preview '\''bat --style=numbers,changes --color=always {}'\'''
    alias lg lazygit
    alias ll 'eza --group-directories-first --icons -la'
    alias ls 'eza --group-directories-first --icons'
    alias lt 'eza --group-directories-first --icons --tree'
    alias nixpc-rebuild 'sudo nixos-rebuild switch --impure --flake ~/.config/dendritic#NIXPC'

    # Interactive shell initialisation
    # Initialize zoxide
    zoxide init fish | source

    # Set environment variables
    set -gx EDITOR nvim
    set -gx VISUAL nvim
    set -gx MANPAGER "nvim +Man!"
    set -gx PATH $HOME/.local/bin $PATH

    # Better history configuration
    set -gx HISTSIZE 10000
    set -gx HISTFILESIZE 10000

    # Hydro prompt configuration
    set -g hydro_symbol_prompt ❱
    set -g hydro_symbol_start '~'
    set -g hydro_symbol_git_dirty •
    set -g hydro_symbol_git_ahead ⇡
    set -g hydro_symbol_git_behind ⇣

    set -g hydro_color_prompt blue
    set -g hydro_color_pwd normal
    set -g hydro_color_git magenta
    set -g hydro_color_error red
    set -g hydro_color_start normal
    set -g hydro_color_duration normal

    set -g hydro_fetch true
    set -g hydro_multiline true

    set -g fish_prompt_pwd_dir_length 2
    set -g hydro_cmd_duration_threshold 1000
    set -g hydro_ignored_git_paths /tmp

    # Enable Vi mode
    fish_vi_key_bindings

    # Configure directory history navigation
    bind \e\[1\;5A history-token-search-backward
    bind \e\[1\;5B history-token-search-forward
    # zoxide + fzf: pick a directory from zoxide history
    bind -M insert \ce zoxide_fzf
    bind -M default \ce zoxide_fzf
    # fzf: pick a subcommand/flag for the current command (e.g. `omp` + Ctrl+F)
    bind -M insert \cf __fzf_search_args
    bind -M default \cf __fzf_search_args

    fastfetch

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "$HOME/.local/share/fish/home-manager/generated_completions" $post
    end

    if not functions -q __direnv_export_eval
        /nix/store/7jf90vcsdcsn54mrydlpdhcrggrppapf-direnv-2.37.1/bin/direnv hook fish | source
    end
end
