
{ pkgs, lib, ... }:

{


  # Containers
  virtualisation.oci-containers.containers."paseo" = {
    image = "paseo-with-agents";
    environment = {
      "PASEO_HOSTNAMES" = "nixpc.tail49d78b.ts.net,.ts.net,nixpc";
      "PASEO_TRUSTED_PROXIES" = "loopback,172.16.0.0/12";
      "PASEO_WEB_UI_ENABLED" = "true";
    };
    volumes = [
      "/mnt/2tb-ext4/paseo/home:/home/paseo:rw"
      "/mnt/2tb-ext4/paseo/workspace:/workspace:rw"
    ];
    ports = [
      "127.0.0.1:6767:6767/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=paseo"
      "--network=paseo_default"
    ];
  };
  systemd.services."docker-paseo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container paseo generated by compose2nix.";
    after = [
      "docker-network-paseo_default.service"
    ];
    requires = [
      "docker-network-paseo_default.service"
    ];
    partOf = [
      "docker-compose-paseo-root.target"
    ];
    wantedBy = [
      "docker-compose-paseo-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-paseo_default" = {
    unitConfig.Description = "Network paseo_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f paseo_default";
    };
    script = ''
      docker network inspect paseo_default || docker network create paseo_default
    '';
    partOf = [ "docker-compose-paseo-root.target" ];
    wantedBy = [ "docker-compose-paseo-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-paseo-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
