# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."wayfinder-dashboard" = {
    image = "wayfinder-dashboard";
    environment = {
      "PORT" = "8787";
    };
    volumes = [
      "/mnt/2tb-ext4/wayfinder-dashboard:/data:rw"
    ];
    ports = [
      "127.0.0.1:8787:8787/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wayfinder-dashboard"
      "--network=wayfinder-dashboard_default"
    ];
  };
  systemd.services."docker-wayfinder-dashboard" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    unitConfig.Description = "Container wayfinder-dashboard generated by compose2nix.";
    after = [
      "docker-network-wayfinder-dashboard_default.service"
    ];
    requires = [
      "docker-network-wayfinder-dashboard_default.service"
    ];
    partOf = [
      "docker-compose-wayfinder-dashboard-root.target"
    ];
    wantedBy = [
      "docker-compose-wayfinder-dashboard-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-wayfinder-dashboard_default" = {
    unitConfig.Description = "Network wayfinder-dashboard_default generated by compose2nix.";
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f wayfinder-dashboard_default";
    };
    script = ''
      docker network inspect wayfinder-dashboard_default || docker network create wayfinder-dashboard_default
    '';
    partOf = [ "docker-compose-wayfinder-dashboard-root.target" ];
    wantedBy = [ "docker-compose-wayfinder-dashboard-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-wayfinder-dashboard-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
