# Core bundle: imported by every host. Composes the base system modules
# nothing can live without, plus the machine's generated filesystem layout.
#
# Like voidarc, hardware-configuration.nix stays OUT of the repo (per-machine,
# regenerated by the installer at /etc/nixos). The pathExists guard keeps the
# flake evaluable on machines that have no install yet; a real target always
# has the file.
{
  self,
  inputs,
  ...
}:
{
  flake.nixosModules.core =
    {
      pkgs,
      lib,
      ...
    }:
    let
      modules = with self.nixosModules; [
        user
        bootloader
        nixSettings
        hardware
        locale
      ];
    in
    {
      imports =
        lib.optional (builtins.pathExists /etc/nixos/hardware-configuration.nix) /etc/nixos/hardware-configuration.nix
        ++ modules;

      services = {
        openssh.enable = true;
        avahi = {
          enable = true;
          nssmdns4 = true;
          openFirewall = true;
        };
      };

      environment.systemPackages = with pkgs; [
        vim
        wget
        curl
        git
        unzip
        p7zip
        usbutils
        lsof
        gvfs
        libnotify
      ];

      system.stateVersion = "25.05";
    };
}
